### ISSUE TITLE
Certificate Profile Configuration Options

### ISSUE THREAD

**Issue by mttcpr** [GSA/fpkilint#1]
Need to define all certificate profile configuration options to be supported in the tool. Options should support specifying existing FPKI profiles and provide flexibility for changes.

Acceptance Criteria:
Minimum viable option set defined and stored on github

**Comment by mttcpr** [comment]
@djpackham @godadada 
Draft profile configuration options attached. What are we missing?
[profile-config.xlsx](https://github.com/GSA/fpki-cert-tool/files/1293277/profile-config.xlsx)

**Comment by djpackham** [comment]
@mttcpr are these three docs below your sources for the profile-config.xlsx?

- [X.509 Certificate and Certificate Revocation List (CRL) Extensions Profile for the Shared Service Providers (SSP) Program](https://www.idmanagement.gov/wp-content/uploads/sites/1171/uploads/fpki-cert-profile-ssp.pdf)
- [Federal Public Key Infrastructure (PKI) X.509 Certificate and CRL Extensions Profile](https://www.idmanagement.gov/wp-content/uploads/sites/1171/uploads/fpki-x509-cert-profiles.pdf)
- [X.509 Certificate and Certificate Revocation List (CRL) Extensions Profile for Personal Identity Verification Interoperable (PIV-I) Cards](https://www.idmanagement.gov/wp-content/uploads/sites/1171/uploads/fpki-pivi-cert-profiles.pdf)

**Comment by mttcpr** [comment]
The configuration options should be a super set of the options that are being exercised in the existing policies. I used a variety of sources including the fpki profiles to put together the option set.

**Comment by djpackham** [comment]
Are encoding tests something useful we should include in the tool such as checking to see if a certificate is properly encoded (i.e. explicit is present when it should be implicit or vice versa)?

**Comment by djpackham** [comment]
I'm liking the switch to using the milestones feature. Can we also make the new "issues" in user story format? 
- As a < type of user >, I want < some goal > so that < some reason >.
Then, in the comments section for the user story we can add the acceptance criteria?

**Comment by mttcpr** [comment]
Minimum viable is completed.
