### ISSUE TITLE
As the USG, I need a system architecture diagram to be able to easily understand the technology involved with building the application 

### ISSUE THREAD

**Issue by djpackham** [GSA/fpkilint#12]
Need a system architecture diagram to be able to easily describe what components are being used to build the system.

**Comment by mttcpr** [comment]
Chunde is working on determining how to store and compare the profiles; once he gets his plan together we'll be able to draw a picture

**Comment by JJediny** [comment]
FWIW https://github.com/GSA/DevSecOps-Infrastructure/tree/master/docs/diagrams

**Comment by godadada** [comment]
Uploaded architecture diagram for review:
https://github.com/GSA/fpkilint/blob/dev/docs/ArchDiag.pptx
