### ISSUE TITLE
As the USG, I need a workflow diagram to be able to easily understand how the system will work and be able to share with others.

### ISSUE THREAD

**Issue by djpackham** [GSA/fpkilint#13]
Acceptance Criteria:
- A detailed workflow that describes the flow of the system and end users.
- Generated using PPT, Visio or similar tool saved in PDF format

**Comment by mttcpr** [comment]
@djpackham Added [Workflow.pdf](https://github.com/GSA/fpkilint/blob/master/docs/Workflow.pdf) to docs.
