### ISSUE TITLE
Decide on Certificate profile storage format

### ISSUE THREAD

**Issue by mttcpr** [GSA/fpkilint#2]
As software needing to store certificate profiles, I need to have a storage format

Acceptance Criteria:
Storage format similar to JSON, YAML

**Comment by djpackham** [comment]
Can we split this into multiple user stories and/or spikes? For instance, not sure if we've nailed down which format we want to use so determining the storage format could be a quick spike?

Examples:
- Spike: Determine best storage format type
- User Story: As a system, I need to be able to store submitted X.509 certificates to be able to parse out the X.509 field values.
- etc.

**Comment by godadada** [comment]
how about use json object in python and index-ed with certificate profile item keys/names?

**Comment by djpackham** [comment]
Sounds good to me. We can always change later if we need to.

**Comment by mttcpr** [comment]
I think we've all agreed on JSON, I believe this issue is ready to be closed.

**Comment by mttcpr** [comment]
Agreed on JSON
