### ISSUE TITLE
How to run fpkilint on Ubuntu?

### ISSUE THREAD

**Issue by 011211** [GSA/fpkilint#43]
I want to run fpkilint-dev on Ubuntu, but it doesn't work properly, and your README file doesn't have detailed steps.
General virtual machines run through the following steps:
1.. / configure (I can't execute it correctly in the first step.error: don't have that file or directory)
2.make
3.make test
4.sudo make install

**Comment by mistial-dev** [comment]
@011211 Does your use case allow you to use the online version at https://cpct.app.cloud.gov/ ?

**Comment by idmken** [comment]
I think this is resolved since moving to a docker version. Please confirm.

**Comment by idmken** [comment]
Updated Readme with docker instructions. #59
